export const PREBUILT_SECTIONS = [
  // General
  { name: 'Chief Complaint', promptHint: null, category: 'general' },
  { name: 'HPI', promptHint: 'History of Present Illness — onset, duration, character, severity, context', category: 'general' },
  { name: 'Past Medical History', promptHint: null, category: 'general' },
  { name: 'Social History', promptHint: null, category: 'general' },
  { name: 'Family History', promptHint: null, category: 'general' },
  { name: 'Medications', promptHint: null, category: 'general' },
  { name: 'Allergies', promptHint: null, category: 'general' },
  { name: 'Review of Systems', promptHint: null, category: 'general' },
  { name: 'Physical Exam', promptHint: null, category: 'general' },
  { name: 'Assessment', promptHint: null, category: 'general' },
  { name: 'Plan', promptHint: null, category: 'general' },
  { name: 'Disposition', promptHint: null, category: 'general' },
  // ICU/Critical Care
  { name: 'Sedation & Analgesia', promptHint: 'Document CPOT/RASS scores, agents used, target levels', category: 'icu' },
  { name: 'Ventilator Management', promptHint: 'Mode, FiO2, PEEP, tidal volume, plateau pressure, compliance', category: 'icu' },
  { name: 'Vasopressor Status', promptHint: 'Current agents, doses, MAP target, hemodynamic response', category: 'icu' },
  { name: 'Lines & Drains', promptHint: 'Document all central/arterial lines, drains, tubes with dates', category: 'icu' },
  { name: 'Infectious Disease', promptHint: 'Active infections, cultures pending/resulted, antibiotics', category: 'icu' },
  { name: 'Neurological Status', promptHint: 'GCS, focal deficits, sedation effects, neuro changes', category: 'icu' },
  { name: 'Renal & Fluid Balance', promptHint: 'Creatinine trend, urine output, fluid balance, CRRT if applicable', category: 'icu' },
  { name: 'Nutrition & GI', promptHint: 'Enteral/parenteral nutrition, GI tolerance, bowel function', category: 'icu' },
  { name: 'Goals of Care', promptHint: 'Patient/family understanding, code status, palliative discussions', category: 'icu' },
  { name: 'Code Status', promptHint: null, category: 'icu' },
  { name: 'Overnight Events', promptHint: 'Significant events, interventions, responses since last note', category: 'icu' },
  { name: 'Pending Studies', promptHint: 'Labs, imaging, cultures, consults not yet resulted', category: 'icu' },
  // Specialty
  { name: 'Procedure Details', promptHint: null, category: 'specialty' },
  { name: 'Operative Findings', promptHint: null, category: 'specialty' },
  { name: 'Discharge Instructions', promptHint: null, category: 'specialty' },
  { name: 'Follow-up Plan', promptHint: null, category: 'specialty' },
  { name: 'Consult Recommendations', promptHint: null, category: 'specialty' },
  { name: 'Reason for Transfer', promptHint: null, category: 'specialty' },
];
